language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate
notifications:
  slack:
    secure: UafYUhxqu99j+eXNlI6fqXiMbpjZ+ahb985WxmFbW+FLqzYxVZZfXvKWTjE03qD0DgdO/cMvnNcx1IHSnnCyuGzyo5B4iI85IuCQi6bMG9rIpqxIQ5CF6Iy2bYVITN1ZyaymEEvLiZmm9PeYyCCoOQp5QXFFTYGzMRnpuyBOC/euvizsRFdZoCfEBl/gaEge8y9NGRsz0MseEwl6wkrkQJalviy22lvo7iH8tVsuv3hWK9KX9oIpCbUrUOdlqpMQ61NncVtt6d73V9cFiIksXK13kbwt7bmJcsDF0KQg+/K8HToTYArB65HRDvoiT7H93GL3cFupa4tGPL4eYKWnspuE0l/1VXnbZCRF82tFIUEABRNkKYGfScaa33WLjjWnAw1GuX+8ZXHjmxWiRt4bW/3TVGn+oaqNN9SbSXDTG3zc2yoankIk2I+TvUUv8PUhe2cMnDgNVEZBfXYdgChJK4mAGp2dE6xufxdn9KZdtl5yPFNPMf10ncJizoQVW8nSy/z3xK9r2qxVXbC5jxM6JmPqIqYrqms+L4NEp600HsroGXSdfSLJdOKKwYDi7hpngjaidAxPCLLl547HDugzxU8VsE7mEntKYrYuYBGAqxnQQ6jwGv0KnVlFtM7RTAXlk0/NBng2dmTY3Q2M+Szj6a6mbTY+EPFMpP/fl4XzJ60=
